name: pypet-test-suite

on:
  push:
    branches: [ master, develop, modernize ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        env:
          - {PYTHON_VERSION: "3.13", COVERAGE: OFF, GIT_TEST: OFF, EXAMPLES: OFF, TEST_SUITE: SINGLECORE, SCOOP: OFF, DEPS: latest}
          - {PYTHON_VERSION: "3.12", COVERAGE: OFF, GIT_TEST: OFF, EXAMPLES: OFF, TEST_SUITE: MULTIPROC, SCOOP: OFF, DEPS: minimum}
    env: ${{ matrix.env }}
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.env.PYTHON_VERSION }}
          auto-activate-base: true
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - run: chmod +x ./.github/scripts/install.sh; ./.github/scripts/install.sh
      - run: chmod +x ./.github/scripts/runtests.sh; ./.github/scripts/runtests.sh
