name: pypet-test-suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Install dependencies for PyTables
  # command to install dependencies
  before_install:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
      - run: sudo apt-get install gfortran libopenblas-dev liblapack-dev libhdf5-serial-dev
      - run: conda info -a
      # Replace dep1 dep2 ... with your dependencies
      - run: conda create -q -n test-environment python=3.10 pip numpy scipy numexpr cython pandas pytables
      - run: conda activate test-environment
      - run: pip freeze
  install:
    needs: before_install
    runs-on: ubuntu-latest
    steps:
      - run: echo "Python $TRAVIS_PYTHON_VERSION"
      - run: echo "+++++++++++ Installing Coveralls if coverage +++++++++++"
      - run: if [[ $COVERAGE == ON ]]; then pip install coveralls; fi
      - run: echo "+++++++++++ Installing Brian2 +++++++++++"
      - run: pip install brian2
      - run: echo "+++++++++++ Installing psutil +++++++++++"
      - run: pip install psutil
      - run: echo "+++++++++++ Installing dill ++++++++++++"
      - run: pip install dill
      - run: echo "+++++++++++ Installing GitPython and Sumatra if needed ++++++++++++"
      - run: if [[ $GIT_TEST == ON ]]; then chmod +x ciscripts/travis/install_gitpython.sh; ciscripts/travis/install_gitpython.sh; fi
      - run: echo "+++++++++++ Installing matplotlib and deap if needed ++++++++++++"
      - run: if [[ $EXAMPLES == ON ]]; then conda install matplotlib; pip install deap; fi
      - run: echo "++++++++++++ Installing SCOOP  +++++++++++++++++++++++++"
      - run: pip install scoop
      - run: echo "+++++++++++ Installing PYPET unless coverage +++++++++++"
      - run: if [[ $COVERAGE == OFF ]]; then python setup.py install; fi
      - run: echo "+++++++++++ FINISHED INSTALL +++++++++++"
  test:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.10
            env: COVERAGE=OFF GIT_TEST=OFF EXAMPLES=OFF TEST_SUITE=SINGLECORE SCOOP=OFF
          - python: 3.11
            env: COVERAGE=OFF GIT_TEST=OFF EXAMPLES=OFF TEST_SUITE=MULTIPROC SCOOP=OFF
          - python: 3.9
            env: COVERAGE=ON GIT_TEST=ON EXAMPLES=OFF TEST_SUITE=OFF SCOOP=OFF
          - python: 3.11
            env: COVERAGE=OFF GIT_TEST=ON EXAMPLES=ON TEST_SUITE=OFF SCOOP=ON
    steps:
      - run: cd ciscripts/; chmod +x runtests.sh; ./runtests.sh


