name: pypet-test-suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Install dependencies for PyTables
  # command to install dependencies
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
      - run: sudo apt-get install gfortran libopenblas-dev liblapack-dev libhdf5-serial-dev
      - run: conda info -a
      - run: echo "$PWD"
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - env: PYTHON_VERSION="3.10" COVERAGE=OFF GIT_TEST=OFF EXAMPLES=OFF TEST_SUITE=SINGLECORE SCOOP=OFF
          - env: PYTHON_VERSION="3.8" COVERAGE=OFF GIT_TEST=OFF EXAMPLES=OFF TEST_SUITE=MULTIPROC SCOOP=OFF
          - env: PYTHON_VERSION="3.9" COVERAGE=ON GIT_TEST=ON EXAMPLES=OFF TEST_SUITE=OFF SCOOP=OFF
          - env: PYTHON_VERSION="3.10" COVERAGE=OFF GIT_TEST=ON EXAMPLES=ON TEST_SUITE=OFF SCOOP=ON
    steps:
      - run: chmod +x ./ciscripts/install.sh; ./ciscripts/install.sh
      - run: cd ciscripts/; chmod +x runtests.sh; ./runtests.sh


